/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RegistrationForm = IDL.Record({
  'major' : IDL.Text,
  'interests' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Text,
  'email' : IDL.Text,
  'university' : IDL.Text,
  'skillLevel' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(RegistrationForm)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [IDL.Record({ 'totalRegistrations' : IDL.Nat })],
      ['query'],
    ),
  'submitRegistration' : IDL.Func([RegistrationForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RegistrationForm = IDL.Record({
    'major' : IDL.Text,
    'interests' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Text,
    'email' : IDL.Text,
    'university' : IDL.Text,
    'skillLevel' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(RegistrationForm)],
        ['query'],
      ),
    'getAnalytics' : IDL.Func(
        [],
        [IDL.Record({ 'totalRegistrations' : IDL.Nat })],
        ['query'],
      ),
    'submitRegistration' : IDL.Func([RegistrationForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };